## Problem 1

Write a function so that the columns of the output matrix are powers of the input
vector.
The order of the powers is determined by the increasing boolean argument. Specifically, when
increasing is False, the i-th output column is the input vector raised element-wise to the power
of N - i - 1.
HINT: Such a matrix with a geometric progression in each row is named for Alexandre-
Theophile Vandermonde.

In [1]:
import numpy as np

def aVandermonde(l, N, increasing = False):
    if increasing:
        print(np.array([ j** i for j in l for i in range(N)]).reshape(len(l), N))
    else:
        print(np.array([ j** (N-1-i) for j in l for i in range(N)]).reshape(len(l), N))
        
mylst = [1,2,3]
N = 4
print('with decreasing ')
print('-'*50)
aVandermonde(np.array(mylst),N)
print('with increasing ')
print('-'*50)
aVandermonde(np.array(mylst),N, increasing= True)

with decreasing 
--------------------------------------------------
[[ 1  1  1  1]
 [ 8  4  2  1]
 [27  9  3  1]]
with increasing 
--------------------------------------------------
[[ 1  1  1  1]
 [ 1  2  4  8]
 [ 1  3  9 27]]


## Problem 2

In [ ]:
Given a sequence of n values x1, x2, ..., xn and a window size k>0, the k-th moving average of
the given sequence is defined as follows:
The moving average sequence has n-k+1 elements as shown below.
The moving averages with k=4 of a ten-value sequence (n=10) is shown below
i 1 2 3 4 5 6 7 8 9 10
===== == == == == == == == == == ==
Input 10 20 30 40 50 60 70 80 90 100
y1 25 = (10+20+30+40)/4
y2 35 = (20+30+40+50)/4
y3 45 = (30+40+50+60)/4
y4 55 = (40+50+60+70)/4
y5 65 = (50+60+70+80)/4
y6 75 = (60+70+80+90)/4
y7 85 = (70+80+90+100)/4
Thus, the moving average sequence has n-k+1=10-4+1=7 values.

In [2]:
def mov_avg(numbers,window_size):
    i= 0
    moving_averages = []
    while i < len(numbers)-window_size+1:
        this_window = numbers[i:i+window_size]
        window_average = sum(this_window)/window_size
        moving_averages.append(window_average)
        i = i + 1
    print(moving_averages)

In [4]:
numbers = [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150]
window_size = 3

In [5]:
mov_avg(numbers,window_size)

[5.0, 4.666666666666667, 5.666666666666667, 6.666666666666667, 9.666666666666666, 28.666666666666668, 49.333333333333336, 72.66666666666667, 84.0, 93.33333333333333, 116.33333333333333]
